// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import  'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3tfpdVtUr3hrj3M17oFORRryFKS5Slo',
    appId: '1:1072256259947:web:5fbd25aab0c7cd1a9c9e2e',
    messagingSenderId: '1072256259947',
    projectId: 'tripfinder-80b85',
    authDomain: 'tripfinder-80b85.firebaseapp.com',
    storageBucket: 'tripfinder-80b85.appspot.com',
    measurementId: 'G-7X674CH2M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGHqtnIECbraaJ2jRTFc21rvWnoDoPHe8',
    appId: '1:1072256259947:android:24c3f03afae14c089c9e2e',
    messagingSenderId: '1072256259947',
    projectId: 'tripfinder-80b85',
    storageBucket: 'tripfinder-80b85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDgsyNBFB7yDFH5IuKhHcpsCwyiKq63-s',
    appId: '1:1072256259947:ios:70578b8fb15d94b39c9e2e',
    messagingSenderId: '1072256259947',
    projectId: 'tripfinder-80b85',
    storageBucket: 'tripfinder-80b85.appspot.com',
    iosBundleId: 'com.example.tripfinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDgsyNBFB7yDFH5IuKhHcpsCwyiKq63-s',
    appId: '1:1072256259947:ios:70578b8fb15d94b39c9e2e',
    messagingSenderId: '1072256259947',
    projectId: 'tripfinder-80b85',
    storageBucket: 'tripfinder-80b85.appspot.com',
    iosBundleId: 'com.example.tripfinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe3tfpdVtUr3hrj3M17oFORRryFKS5Slo',
    appId: '1:1072256259947:web:7e9b863d75ce72de9c9e2e',
    messagingSenderId: '1072256259947',
    projectId: 'tripfinder-80b85',
    authDomain: 'tripfinder-80b85.firebaseapp.com',
    storageBucket: 'tripfinder-80b85.appspot.com',
    measurementId: 'G-G1QVJG1JJ0',
  );
}
